### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NoodlesDev987** [Suggester/Suggester#211]
Add more slash commands

**Comment by Suspense4615** [comment]
Hello, 
What commands would you like to see implemented as slash commands?

**Comment by NoodlesDev987** [comment]
Idk, but commands in category suggestions should be slash commands

**Comment by Suspense4615** [comment]
then you don't need to open an issue for that, slash commands are already planned

**Comment by BrightnessTM** [comment]
I'm going to close this issue, if you have any further suggestions please let us know on the [support server](https://discord.gg/G5pEdUp)!
