### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Badgaming01** [Suggester/Suggester#228]
Where will I put the token just confused?

**Comment by bwhybrow23** [comment]
Change the name of the `config.json.example` to just `config.json` and put it in there

**Comment by bwhybrow23** [comment]
Change the file `.env.example` to just `.env` and put it there https://github.com/Suggester/Suggester/blob/v4.10.3/.env.example

**Comment by aydenbg** [comment]
> Where will I put the token just confused?

i think ur supposed to add it to a alredy made code if u use repl.it u can just type discord.js starter and there is alredy a starter code there and u can just add this to it

**Comment by Suspense4615** [comment]
Self-hosting is not supported

**Comment by bwhybrow23** [comment]
If that's the case, then create a license that says that. At the moment, the little piece of text in the ReadMe won't withhold in a copyright claim. You need a license that states self hosting isn't allowed. More specifically, hosting for commercial benefits, as in order for someone to contribute properly, they'd need to run their own version of the bot to check everything works fine.

**Comment by Suspense4615** [comment]
A license is something we plan to add in the future, and as mentioned in the read me you can selfhost for private use and/or testing changes. We just won't provide support on how to do it, both here and in the support server.
