### ISSUE TITLE
Selfhosting on public server

### ISSUE THREAD

**Issue by Oman395** [Suggester/Suggester#235]
Hey there, the readme says "We do not allow people to host their own clone of Suggester publicly or provide support for it."-- does this mean that you don't want it on a public server, or that you don't want people hosting clones of it for other servers? I'm looking into selfhosting this for our server and I'm not sure whether it will be OK. Thanks!

**Comment by AlmostSuspense** [comment]
Hi @Oman395, you can host it for a public server, what we do forbid is to host public instances of the bot (as in, that anyone can add to their server)

**Comment by Oman395** [comment]
Thanks!
